loginapp/loginapp/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^admin/', include('adminapp.urls', namespace='adminapp', app_name='adminapp')),
    url(r'^', include('mainapp.urls', namespace='mainapp', app_name='mainapp')),
]

loginapp/mainapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/?$', views.login, name='login'),
    url(r'^signup/?$', views.signup, name='signup'),
    url(r'^profile/?$', views.profile, name='profile'),
    url(r'^logout/?$', views.logout, name='logout'),
]

loginapp/mainapp/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.utils.translation import ugettext_lazy as _
from django.db import models

class MyUserManager(BaseUserManager):
    def create_user(self, username, email, password=None, commit=True):
        # Username is required
        if not username:
            raise ValueError(_('A username is required'))

        # Email is required
        if not email:
            raise ValueError(_('An email is required'))

        # Create user and set password
        user = self.model(username=username, email=self.normalize_email(email))
        user.set_password(password)

        # Avoid saving if going to be called by create_superuser()
        if commit:
            user.save(using=self._db)

        return user

    def create_superuser(self, username, email, password=None, commit=True):
        # Create superuser, set password and flag as admin
        user = self.create_user(username, email, password, commit=False)
        user.is_active = True
        user.is_admin = True

        if commit:
            user.save(using=self._db)

        return user

class User(AbstractBaseUser):
    username = models.CharField(max_length=100, unique=True, default='')
    email = models.CharField(max_length=100, unique=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    objects = MyUserManager()
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.username

    def get_full_name(self):
        return self.username

    def get_short_name(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return self.is_admin

    @property
    def is_staff(self):
        return self.is_admin

class EmailJob(models.Model):
    destination = models.CharField(max_length=100)
    status = models.CharField(max_length=10, default='pending')
    retry_count = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    last_retry_at = models.DateTimeField(null=True)
    celery_id = models.CharField(max_length=255, null=True)

    def __str__(self):
        return self.destination

loginapp/mainapp/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from . import models

class SignupForm(forms.ModelForm):
    email = forms.EmailField(label=_('Email'))
    password = forms.CharField(label=_('Password'), widget=forms.PasswordInput)
    password_confirmation = forms.CharField(label=_('Password confirmation'), widget=forms.PasswordInput)

    class Meta:
        model = models.User
        fields = ('username', 'email',)

    def clean_password_confirmation(self):
        password = self.cleaned_data.get('password')
        password_confirmation = self.cleaned_data.get('password_confirmation')

        # Check if both passwords are identical
        if password and password_confirmation and password != password_confirmation:
            raise forms.ValidationError(_('Passwords need to be identical'))

        return password_confirmation

    def save(self, commit=True):
        # Save hashed, salted password
        user = super(SignupForm, self).save(commit=False)
        user.set_password(self.cleaned_data.get('password'))
        user.is_active = True
        
        # Start email task
        from . import tasks
        tasks.send_email(self.cleaned_data.get('email'))

        if commit:
            user.save()

        return user

loginapp/mainapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import views as auth_views
from django.contrib import messages, auth
from django.utils.translation import ugettext as _
from django.core.urlresolvers import reverse
from . import forms

# Index view, right now all it does is redirect to user panel
def index(request):
    return signup(request)

# Login view, logs the user in, contrib.auth handles it
def login(request):
    # Check if the user isn't already logged in
    if request.user.is_authenticated():
        return redirect('mainapp:profile')

    return auth_views.login(request, template_name='mainapp/login.html')

# Registers the user into the website
def signup(request):
    # Check if the user is already logged in
    if request.user.is_authenticated():
        return redirect('mainapp:profile')

    if request.method == 'POST':
        form = forms.SignupForm(request.POST)
        if form.is_valid():
            # Save user to the database
            form.save()

            # Redirect to login page
            messages.success(request, _('You have been successfully registered'))
            return redirect('mainapp:login')
    else:
        form = forms.SignupForm()

    return render(request, 'mainapp/signup.html', {
        'form': form
    })

# Shows the user's profile
def profile(request):
    # Check if the user is actually authenticated
    if not request.user.is_authenticated():
        return auth_views.redirect_to_login(
            request.get_full_path(),
            reverse('mainapp:login', current_app='mainapp')
        )

    return render(request, 'mainapp/profile.html')

# Logs the user out
def logout(request):
    if request.user.is_authenticated():
        auth.logout(request)
        messages.info(request, _('Successfully logged out'))

    return redirect('mainapp:index')

loginapp/mainapp/templates/mainapp/accounts_profile.html
{% extends "mainapp/partials/base.html" %}

{% block content %}
  You are logged in as {{ request.user }}<br/>
  <a href="{% url 'mainapp:accounts_logout' %}">Logout »</a>
{% endblock content %}

loginapp/mainapp/templates/mainapp/login.html
{% extends "mainapp/partials/base.html" %}

{% block body_class %}{{ block.super }} small-container{% endblock body_class %}
{% block content %}
  <div class="container">
    <h2>Log in</h2>
    <p>
      Don't have an account? <a href="{% url 'mainapp:signup' %}">Sign Up »</a>
    </p>
    <form method="post">
      {% csrf_token %}
      {{ form.non_field_errors }}
      <div class="row form-group">
        <div class="col-sm-12 field-{{ form.username.name }} {{ form.username.errors|yesno:'error,' }}">
          <label for="{{ form.username.id_for_label }}">{{ form.username.label }}</label>
          <div class="widget">{{ form.username }}</div>
          {% if form.username.errors %}
            <div class="cal-sm12">
              {{ form.username.errors }}
            </div>
          {% endif %}
        </div>
      </div>
      <div class="row form-group">
        <div class="col-sm-12 field-{{ form.password.name }} {{ form.password.errors|yesno:'error,' }}">
          <label for="{{ form.password.id_for_label }}">{{ form.password.label }}</label>
          <div class="widget">{{ form.password }}</div>
          {% if form.password.errors %}
            <div class="cal-sm12">
              {{ form.password.errors }}
            </div>
          {% endif %}
        </div>
      </div>
      <p class="text-right">
        <button type="submit" class="btn btn-lg btn-primary">Login »</button>
      </p>
    </form>
  </div>
{% endblock content %}

loginapp/mainapp/templates/mainapp/profile.html
{% extends "mainapp/partials/base.html" %}

{% block body_class %}{{ block.super }} small-container{% endblock body_class %}

{% block content %}
  <div class="container">
    You are logged in as `{{ request.user }}`<br/>
    <a href="{% url 'mainapp:logout' %}">Logout »</a>
  </div>
{% endblock content %}

loginapp/mainapp/templates/mainapp/signup.html
{% extends "mainapp/partials/base.html" %}

{% block body_class %}{{ block.super }} small-container{% endblock body_class %}

{% block content %}
  <div class="container">
    <h2>Sign Up</h2>
    <p>
      Already a member? <a href="{% url 'mainapp:login' %}">Log in »</a>
    </p>
    <form method="POST">
      {% csrf_token %}
      <div class="row form-group">
        <div class="col-sm-12 {{ form.username.errors|yesno:'error,' }}">
          <label for="{{ form.username.id_for_label }}">{{ form.username.label }}</label>
          <div class="widget">
            {{ form.username }}
          </div>
          {% if form.username.errors %}
            <div class="col-sm-12">
              {{ form.username.errors }}
            </div>
          {% endif %}
        </div>
      </div>
      <div class="row form-group">
        <div class="col-sm-12 {{ form.email.errors|yesno:'error,' }}">
          <label for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
          <div class="widget">
            {{ form.email }}
          </div>
          {% if form.email.errors %}
            <div class="col-sm-12">
              {{ form.email.errors }}
            </div>
          {% endif %}
        </div>
      </div>
      <div class="row form-group">
        <div class="col-sm-12 {{ form.password.errors|yesno:'error,' }}">
          <label for="{{ form.password.id_for_label }}">{{ form.password.label }}</label>
          <div class="widget">
            {{ form.password }}
          </div>
          {% if form.password.errors %}
            <div class="col-sm-12">
              {{ form.password.errors }}
            </div>
          {% endif %}
        </div>
      </div>
      <div class="row form-group">
        <div class="col-sm-12 {{ form.password_confirmation.errors|yesno:'error,' }}">
          <label for="{{ form.password_confirmation.id_for_label }}">{{ form.password_confirmation.label }}</label>
          <div class="widget">
            {{ form.password_confirmation }}
          </div>
          {% if form.password_confirmation.errors %}
            <div class="col-sm-12">
              {{ form.password_confirmation.errors }}
            </div>
          {% endif %}
        </div>
      </div>
      <div class="text-right">
        <button type="submit" class="btn btn-lg btn-primary">Sign Up »</button>
      </div>
    </form>
  </div>
{% endblock content %}