loginapp/adminapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^mailjobs/active$', views.mailjobs_active, name='mailjobs_active'),
    url(r'^mailjobs(?:/all)?$', views.mailjobs_all, name='mailjobs_all'),
    url(r'^mailjobs/rest/get$', views.mailjobs_rest_get, name='mailjobs_rest_get'),
    url(r'^notifications/rest/get$', views.notifications_rest_get, name='notifications_rest_get'),
]

loginapp/loginapp/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^admin/', include('adminapp.urls', namespace='adminapp', app_name='adminapp')),
    url(r'^', include('mainapp.urls', namespace='mainapp', app_name='mainapp')),
]

loginapp/mainapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/?$', views.login, name='login'),
    url(r'^signup/?$', views.signup, name='signup'),
    url(r'^profile/?$', views.profile, name='profile'),
    url(r'^logout/?$', views.logout, name='logout'),
]

loginapp/adminapp/models.py
from django.db import models
from mainapp.models import User

class Notification(models.Model):
    kind = models.CharField(max_length=100, blank=True)
    content = models.CharField(max_length=255)
    link = models.CharField(max_length=255, blank=True)
    users = models.ManyToManyField(User, through='UserNotification')
    time = models.DateTimeField(auto_now_add=True)

    def natural_key(self):
        return {
            'kind': self.kind,
            'content': self.content,
            'link': self.link
        }

class UserNotification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    notification = models.ForeignKey(Notification, on_delete=models.CASCADE)
    unread = models.BooleanField(default=True)

loginapp/adminapp/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

class AdminLoginForm(forms.Form):
    username = forms.CharField(label=_('Username'))
    password = forms.CharField(label=_('Password'), widget=forms.PasswordInput)

    def clean(self):
        from django.contrib import auth

        cleaned_data = super(AdminLoginForm, self).clean()

        username = cleaned_data.get('username')
        password = cleaned_data.get('password')
        user = auth.authenticate(username=username, password=password)

        if user is None or not user.is_active:
            self.add_error(forms.forms.NON_FIELD_ERRORS, _('Username or password are incorrect'))

        if user is not None and not user.is_staff:
            self.add_error(forms.forms.NON_FIELD_ERRORS, _('Only staff can log in to the administration panel'))

        self.__authenticated_user = user

        return cleaned_data

    def authenticated_user(self):
        return self.__authenticated_user

loginapp/adminapp/views.py
from django.shortcuts import render, redirect
from django.contrib import auth, messages
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext as _
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponse
from mainapp.models import EmailJob
from django.core import serializers
from django.core.paginator import Paginator
from . import forms, models
from mainapp import models as main_models

def staff_only(user):
    return user.is_authenticated() and user.is_staff

@user_passes_test(staff_only, login_url='adminapp:login')
def dashboard(request):
    return render(request, 'adminapp/dashboard.html', {})

def login(request):
    if request.user.is_authenticated() and request.user.is_staff:
        return redirect('adminapp:dashboard')

    # Create temporary admin for testing
    if not main_models.User.objects.filter(is_admin=True).exists():
        admin_user = main_models.User(username='admin', email='admin@localhost')
        admin_user.set_password('admin')
        admin_user.save()

    if request.method == 'POST':
        form = forms.AdminLoginForm(request.POST)
        if form.is_valid():
            # Log out the current non-admin user, if any
            if request.user.is_authenticated():
                auth.logout(request)

            # Login the user
            auth.login(request, form.authenticated_user())

            # Go to the dashboard
            return redirect('adminapp:dashboard')
    else:
        form = forms.AdminLoginForm()

    return render(request, 'adminapp/login.html', {
        'form': form
    })

def logout(request):
    if request.user.is_authenticated() and request.user.is_staff:
        auth.logout(request)
        messages.info(request, _('Successfully logged out'))

    return redirect('adminapp:login') # Or to the main site?

@user_passes_test(staff_only, login_url='adminapp:login')
def mailjobs_all(request):
    return render(request, 'adminapp/mailjobs_all.html')

@user_passes_test(staff_only, login_url='adminapp:login')
def mailjobs_active(request):
    mail_jobs = EmailJob.objects.filter(status__in=['pending', 'started', 'retrying']).order_by('-created_at')

    return render(request, 'adminapp/mailjobs_active.html', {
        'initial_entries': serializers.serialize('json', mail_jobs)
    })

@user_passes_test(staff_only, login_url='adminapp:login')
def mailjobs_rest_get(request):
    if request.method == 'POST':
        page_size = int(request.POST.get('page_size', 10))
        page = request.POST.get('page', 1)
        order_by = request.POST.get('sort_by', 'created_at')
        order_dir = '' if request.POST.get('sort_dir', 'asc') == 'asc' else '-'

        mail_jobs = EmailJob.objects.order_by(order_dir + order_by)
        paginator = Paginator(mail_jobs, page_size)

        page_jobs = serializers.serialize('json', paginator.page(page).object_list)
        json_output = '{"total_count": %i, "entries": %s}' % (mail_jobs.count(), page_jobs)

    else:
        json_output = ''

    return HttpResponse(json_output, content_type="application/json")

@user_passes_test(staff_only, login_url='adminapp:login')
def notifications_rest_get(request):
    if request.method == 'POST':
        load_fields = ('unread', 'notification',)
        notifications = models.UserNotification.objects.filter(user_id=request.user.pk, unread=True)\
            .order_by('-notification__time') # Can't order by notification time for some reason, by id plays nicely too
        notifications_count = notifications.count()

        # If number of unread notifications is less than six
        if notifications_count < 6:
            more_notifications = models.UserNotification.objects.filter(user_id=request.user.pk, unread=False)\
                .order_by('-notification__time')
            more_notifications = more_notifications[:6 - notifications_count]
            notifications = list(notifications) + list(more_notifications)

        json_output = serializers.serialize('json', notifications, fields=load_fields, use_natural_foreign_keys=True)
    else:
        json_output = ''

    return HttpResponse(json_output, content_type="application/json")

loginapp/adminapp/templates/adminapp/partials/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-COMPATIBLE" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>{% block title %}Tech assignment :: Administration{% endblock title %}</title>

  {# Bootstrap #}
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

  {# Main style #}
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

  {# Admin style #}
  <link rel="stylesheet" type="text/css" href="{% static 'css/admin.css' %}">
</head>
<body class="{% block body_class %}{% endblock %}">
<div id="wrapper" class="content">
  {# header block #}
  {% block header %}
    
  {% endblock header %}

  {# Show messages if any #}
  {% block messages %}
    {% if messages %}
      <div class="container messages">
        {% for msg in messages %}
          <div class="alert alert-{{ msg.level_tag }}" role="alert">{{ msg.message }}</div>
        {% endfor %}
      </div>
    {% endif %}
  {% endblock messages %}

  {# Show page content #}
  {% block dash_container %}
    {% block content %}
      
    {% endblock content %}
  {% endblock dash_container %}

  {# Extra scripts #}
  {% block extra_scripts %}
    
  {% endblock extra_scripts %}
</div>
</body>
</html>

loginapp/adminapp/templates/adminapp/partials/base_site.html
{% extends "adminapp/partials/base.html" %}
{% load static %}

{% block header %}
  <header id="header">
    <div class="container">
      <div class="row">
        <div class="col-sm-6 page-title">
          <h1><a href="{% url 'adminapp:dashboard' %}">Administration</a></h1>
          <notifications
            :notification-count="notificationCount">
          </notifications>
        </div>
        <div class="col-sm-6 admin-links">
          Logged in as {{ request.user }} | <a href="{% url 'adminapp:logout' %}">Logout »</a>
        </div>
      </div>
    </div>
  </header>
{% endblock header %}

{% block dash_container %}
  <div class="container dash-container">
    <div class="row">
      <div class="col-sm-3 col-sm-push-9">
        {% block sidebar %}
          <ul>
            <li><a href="{% url 'adminapp:mailjobs_all' %}">Mail jobs (All)</a></li>
            <li><a href="{% url 'adminapp:mailjobs_active' %}">Mail jobs (Active)</a></li>
          </ul>
        {% endblock sidebar %}
      </div>
      <div class="col-sm-9 col-sm-pull-3">
        {% block content %}
          
        {% endblock content %}
      </div>
    </div>
  </div>
{% endblock dash_container %}

{% block extra_scripts %}
  {{ block.super }}
  <script type="text/javascript" src="{% static 'js/vue.js' %}"></script>

  <script type="text/x-template" id="notifications-script">
    {% verbatim %}
    <div id="notifications">
      <a href="#" class="count" @click="toggleWindow()">{{ notificationCount }}</a>
      <div class="window-screen" :class="windowOpen ? 'open' : ''" @click="toggleWindow()"></div>
      <ul class="window" :class="windowOpen ? 'open' : ''">
        <li v-for="entry in entries" :class="[entry.fields.unread ? 'unread' : 'read', entry.fields.notification.kind]">
          <a :href="entry.fields.notification.link">{{ entry.fields.notification.content }}</a>
        </li>
      </ul>
    </div>
    {% endverbatim %}
  </script>

  <script type="text/javascript" src="{% static 'js/admin-notifications.js' %}"></script>
  <script type="text/javascript">
    adminNotifications("{% url 'adminapp:notifications_rest_get' %}");
  </script>

{% endblock extra_scripts %}