loginapp/adminapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^mailjobs/active$', views.mailjobs_active, name='mailjobs_active'),
    url(r'^mailjobs(?:/all)?$', views.mailjobs_all, name='mailjobs_all'),
    url(r'^mailjobs/rest/get$', views.mailjobs_rest_get, name='mailjobs_rest_get'),
    url(r'^notifications/rest/get$', views.notifications_rest_get, name='notifications_rest_get'),
]

loginapp/loginapp/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^admin/', include('adminapp.urls', namespace='adminapp', app_name='adminapp')),
    url(r'^', include('mainapp.urls', namespace='mainapp', app_name='mainapp')),
]

loginapp/mainapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/?$', views.login, name='login'),
    url(r'^signup/?$', views.signup, name='signup'),
    url(r'^profile/?$', views.profile, name='profile'),
    url(r'^logout/?$', views.logout, name='logout'),
]

loginapp/adminapp/models.py
from django.db import models
from mainapp.models import User

class Notification(models.Model):
    kind = models.CharField(max_length=100, blank=True)
    content = models.CharField(max_length=255)
    link = models.CharField(max_length=255, blank=True)
    users = models.ManyToManyField(User, through='UserNotification')
    time = models.DateTimeField(auto_now_add=True)

    def natural_key(self):
        return {
            'kind': self.kind,
            'content': self.content,
            'link': self.link
        }

class UserNotification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    notification = models.ForeignKey(Notification, on_delete=models.CASCADE)
    unread = models.BooleanField(default=True)

loginapp/adminapp/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

class AdminLoginForm(forms.Form):
    username = forms.CharField(label=_('Username'))
    password = forms.CharField(label=_('Password'), widget=forms.PasswordInput)

    def clean(self):
        from django.contrib import auth

        cleaned_data = super(AdminLoginForm, self).clean()

        username = cleaned_data.get('username')
        password = cleaned_data.get('password')
        user = auth.authenticate(username=username, password=password)

        if user is None or not user.is_active:
            self.add_error(forms.forms.NON_FIELD_ERRORS, _('Username or password are incorrect'))

        if user is not None and not user.is_staff:
            self.add_error(forms.forms.NON_FIELD_ERRORS, _('Only staff can log in to the administration panel'))

        self.__authenticated_user = user

        return cleaned_data

    def authenticated_user(self):
        return self.__authenticated_user

loginapp/adminapp/views.py
from django.shortcuts import render, redirect
from django.contrib import auth, messages
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext as _
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponse
from mainapp.models import EmailJob
from django.core import serializers
from django.core.paginator import Paginator
from . import forms, models
from mainapp import models as main_models

def staff_only(user):
    return user.is_authenticated() and user.is_staff

@user_passes_test(staff_only, login_url='adminapp:login')
def dashboard(request):
    return render(request, 'adminapp/dashboard.html', {})

def login(request):
    if request.user.is_authenticated() and request.user.is_staff:
        return redirect('adminapp:dashboard')

    # Create temporary admin for testing
    if not main_models.User.objects.filter(is_admin=True).exists():
        admin_user = main_models.User(username='admin', email='admin@localhost')
        admin_user.set_password('admin')
        admin_user.save()

    if request.method == 'POST':
        form = forms.AdminLoginForm(request.POST)
        if form.is_valid():
            # Log out the current non-admin user, if any
            if request.user.is_authenticated():
                auth.logout(request)

            # Login the user
            auth.login(request, form.authenticated_user())

            # Go to the dashboard
            return redirect('adminapp:dashboard')
    else:
        form = forms.AdminLoginForm()

    return render(request, 'adminapp/login.html', {
        'form': form
    })

def logout(request):
    if request.user.is_authenticated() and request.user.is_staff:
        auth.logout(request)
        messages.info(request, _('Successfully logged out'))

    return redirect('adminapp:login') # Or to the main site?

@user_passes_test(staff_only, login_url='adminapp:login')
def mailjobs_all(request):
    return render(request, 'adminapp/mailjobs_all.html')

@user_passes_test(staff_only, login_url='adminapp:login')
def mailjobs_active(request):
    mail_jobs = EmailJob.objects.filter(status__in=['pending', 'started', 'retrying']).order_by('-created_at')

    return render(request, 'adminapp/mailjobs_active.html', {
        'initial_entries': serializers.serialize('json', mail_jobs)
    })

@user_passes_test(staff_only, login_url='adminapp:login')
def mailjobs_rest_get(request):
    if request.method == 'POST':
        page_size = int(request.POST.get('page_size', 10))
        page = request.POST.get('page', 1)
        order_by = request.POST.get('sort_by', 'created_at')
        order_dir = '' if request.POST.get('sort_dir', 'asc') == 'asc' else '-'

        mail_jobs = EmailJob.objects.order_by(order_dir + order_by)
        paginator = Paginator(mail_jobs, page_size)

        page_jobs = serializers.serialize('json', paginator.page(page).object_list)
        json_output = '{"total_count": %i, "entries": %s}' % (mail_jobs.count(), page_jobs)

    else:
        json_output = ''

    return HttpResponse(json_output, content_type="application/json")

@user_passes_test(staff_only, login_url='adminapp:login')
def notifications_rest_get(request):
    if request.method == 'POST':
        load_fields = ('unread', 'notification',)
        notifications = models.UserNotification.objects.filter(user_id=request.user.pk, unread=True)\
            .order_by('-notification__time') # Can't order by notification time for some reason, by id plays nicely too
        notifications_count = notifications.count()

        # If number of unread notifications is less than six
        if notifications_count < 6:
            more_notifications = models.UserNotification.objects.filter(user_id=request.user.pk, unread=False)\
                .order_by('-notification__time')
            more_notifications = more_notifications[:6 - notifications_count]
            notifications = list(notifications) + list(more_notifications)

        json_output = serializers.serialize('json', notifications, fields=load_fields, use_natural_foreign_keys=True)
    else:
        json_output = ''

    return HttpResponse(json_output, content_type="application/json")

loginapp/adminapp/templates/adminapp/dashboard.html
{% extends "adminapp/partials/base_site.html" %}

{% block content %}
  <h2>Dashboard</h2>
  <p>TODO</p>
{% endblock content %}

loginapp/adminapp/templates/adminapp/login.html
{% extends "adminapp/partials/base.html" %}

{% block body_class %}{{ block.super }} small-container{% endblock body_class %}

{% block content %}
  <div class="container">
    <h2>Admin Log in</h2>
    <p>
      <a href="{% url 'mainapp:index' %}">« Back to the main site</a>
    </p>
    <form method="post">
      {% csrf_token %}
      {{ form.non_field_errors }}
      <div class="row form-group">
        <div class="col-sm-12 field-{{ form.username.name }} {{ form.username.errors|yesno:'error,' }}">
          <label for="{{ form.username.id_for_label }}">{{ form.username.label }}</label>
          <div class="widget">{{ form.username }}</div>
          {% if form.username.errors %}
            <div class="cal-sm12">
              {{ form.username.errors }}
            </div>
          {% endif %}
        </div>
      </div>
      <div class="row form-group">
        <div class="col-sm-12 field-{{ form.password.name }} {{ form.password.errors|yesno:'error,' }}">
          <label for="{{ form.password.id_for_label }}">{{ form.password.label }}</label>
          <div class="widget">{{ form.password }}</div>
          {% if form.password.errors %}
            <div class="cal-sm12">
              {{ form.password.errors }}
            </div>
          {% endif %}
        </div>
      </div>
      <p class="text-right">
        <button type="submit" class="btn btn-lg btn-primary">Login »</button>
      </p>
    </form>
  </div>
{% endblock content %}

loginapp/adminapp/templates/adminapp/mailjobs_active.html
{% extends "adminapp/partials/base_site.html" %}
{% load static %}

{% block content %}
  <div id="mail-jobs">
    <h2>Mail jobs (active)</h2>
    <datatable class="jobs-list" :columns="columns" :data-store="dataStore" sortable></datatable>
  </div>
{% endblock content %}

{% block extra_scripts %}
  {{ block.super }}
  <script type="text/javascript" src="{% static 'js/vuejs-datatable.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/mailjobs-active.js' %}"></script>
  <script type="text/javascript">
    mailjobs_active('{{ initial_entries|safe }}');
  </script>
{% endblock extra_scripts %}

loginapp/adminapp/templates/adminapp/mailjobs_all.html
{% extends "adminapp/partials/base_site.html" %}
{% load static %}

{% block content %}
  <div id="mail-jobs">
    <h2>Mail jobs (all)</h2>
    <datatable class="jobs-list" :columns="columns" :data-store="dataStore" sortable paginate></datatable>
  </div>
{% endblock content %}

{% block extra_scripts %}
  {{ block.super }}
  <script type="text/javascript" src="{% static 'js/vuejs-datatable.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/mailjobs-all.js' %}"></script>
  <script type="text/javascript">
    mailjobs_all("{% url 'adminapp:mailjobs_rest_get' %}");
  </script>
{% endblock extra_scripts %}